# Generated by Django 3.1.7 on 2021-03-01 08:49

import datetime_utils.date_time
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=160)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True)),
                ('created_date', models.DateField(default=datetime_utils.date_time.DateTime.datenow)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wallets',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateField(default=datetime_utils.date_time.DateTime.datenow)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_models.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletAdjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True)),
                ('created_date', models.DateField(default=datetime_utils.date_time.DateTime.datenow)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_models.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_models.walletcurrency'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'wallet')},
        ),
    ]
