# Generated by Django 3.1.7 on 2021-03-03 14:25

import django_datetime.date_time
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_models', '0002_auto_20210303_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateField(default=django_datetime.date_time.datetime.dnow())),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_models.wallet')),
            ],
        ),
    ]
